### ISSUE TITLE
Connect sortinghat with Dockerhub

### ISSUE THREAD

**Issue by andygrunwald** [MetricsGrimoire/sortinghat#43]
To get the full benefit from the Dockerfile it would be cool to connect this Github repository with Dockerhub and add a automated build: https://hub.docker.com/

I can`t do this, because i am not part of the sortinghat team.

What you have to do for this:
1. Visit https://hub.docker.com/
2. Register
3. Connect your Github account
4. Create a new automated build
5. Add Dockerhub as a webhook
6. Enjoy

With this people don`t have to build the docker image on their own. Instead the can just use it and hit `docker run ...` and everything will be downloaded.

If you need help to do this, please let me know. I will be happy to help!

**Comment by andygrunwald** [comment]
Any update here?

**Comment by sduenas** [comment]
Hey Andy, I've been out last days and I completely forgot about this.

I think is a great idea to have automated builds of sortinghat. Let me check it!

**Comment by andygrunwald** [comment]
THX Santi.
If i can help, ping me!

**Comment by sduenas** [comment]
@andygrunwald 

Here you have it!

https://hub.docker.com/r/grimoirelab/sortinghat/

I had to add it to grimoirelab (the new organization where we started to develop the new generation of tools) because Metrics Grimoire org was already taken. Maybe it was you :-D

BTW, https://github.com/grimoirelab

**Comment by andygrunwald** [comment]
@sduenas Oh yes. I own the MericsGrimoire group. But i added you as an owner. See https://hub.docker.com/u/metricsgrimoire/dashboard/teams/owners/

Feel free to drop me as an owner. I can`t delete myself.

Thanks for adding it to Dockerhub. Now everyone can extend it :)

**Comment by andygrunwald** [comment]
@sduenas Will you move sortinghat to the metricsgrimoire organisation? Or will it stay at grimoirelab?
If second, we have to modify the readme docker commands.
Let me know, then i will do it.

**Comment by sduenas** [comment]
@andygrunwald Oh great! You can stay as owner as well. You're part of metrics grimoire so no problem. I added an automatic build on metrics grimoire and I'm going to remove it from grimoirelab. Let's keep things organized as they are now.

Thanks again! I close this ticket because the first image is now available.
